### ISSUE TITLE
Waktu Solat Terengganu undefined

### ISSUE THREAD

**Issue by Habibah28** [afzafri/Waktu-Solat-API#2]
Waktu solat untuk Terengganu dapat undefined untuk setiap zone. Lain-lain negeri tiada masalah.

Contoh: .../api.php?zon=TRG01

Result: {"kod_zon":"TRG01","nama_zon":"Kuala Terengganu, Marang","tarikh_masa":"30-04-2018 17:24:04"}

![image](https://user-images.githubusercontent.com/15159019/39421511-fbe2994c-4c9b-11e8-83b7-838c3781b95d.png)

Contoh: .../api.php?zon=SGR03

Result: {"waktu_imsak":"05:35 a.m.","waktu_subuh":"05:45 a.m.","waktu_syuruk":"07:03 a.m.","waktu_zohor":"01:13 a.m.","waktu_asar":"04:31 a.m.","waktu_maghrib":"07:20 a.m.","waktu_isyak":"08:31 a.m.","kod_zon":"SGR03","nama_zon":"Kuala Lumpur","tarikh_masa":"30-04-2018 14:51:27"}

![image](https://user-images.githubusercontent.com/15159019/39421527-0b76c25c-4c9c-11e8-8518-93014d60918e.png)

**Comment by afzafri** [comment]
Terima kasih untuk maklum balas ini. Isu ni nampaknya berpunca dari laman rasmi e-solat JAKIM. Data untuk Terengganu tak dipaparkan
http://www2.e-solat.gov.my/xml/today/?zon=TRG01

**Comment by afzafri** [comment]
Issue solved. JAKIM changed the XML source URL, hence resulting in the "undefined" problems for all the prayer time for each states. 
API Updated to scrape from the new XML source URL
