### ISSUE TITLE
Waktu solat tidak muncul

### ISSUE THREAD

**Issue by ikmal989** [afzafri/Waktu-Solat-API#4]
Assalamualaikum. terima kasih kerana menyediakan source code. tapi ada beberapa daerah waktu solat tidak dipaparkan. antaranya daerah langkawi dan puncak gunung jerai di Kedah dan beberapa daerah di Perak.
![errorsolat](https://user-images.githubusercontent.com/79139114/108045096-08289680-707e-11eb-932f-708dc6ac6390.PNG)

**Comment by afzafri** [comment]
Masih berfungsi. Kadang2 JAKIM update jadual waktu solat, jadi mungkin waktu solat tak ada waktu tengah update.
![image](https://user-images.githubusercontent.com/14824387/108309847-51e3bf00-71ed-11eb-8e2f-78d252fcc888.png)
![image](https://user-images.githubusercontent.com/14824387/108309863-590acd00-71ed-11eb-8f71-52b765cbc824.png)

**Comment by ikmal989** [comment]
thanks
